[project]
name = "xtensor-fmt"
version = "0.0.1"
description = "<fmt> adapters for xtensor"
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64"]
license = "MIT"
license-file = "LICENSE"
readme = "readme.org"
repository = "https://github.com/xtslibs/xtensor-fmt"

[tasks]

[dependencies]
xtensor-io = "0.13.0.*"
xtensor = "0.24.6.*"
fmt = "10.1.1.*"
catch2 = "3.4.0.*"
cppcheck = "2.10.3.*"
cpplint = "1.6.0.*"
pkg-config = "0.29.2.*"
cmake = "3.27.5.*"
ninja = "1.11.1.*"
meson = "1.2.1.*"
